### ISSUE TITLE
Not compatible with current pi-base/viewer

### ISSUE THREAD

**Issue by ilcharle** [pi-base/core#22]
Thanks for running this project, it seems pretty neat!

Currently the viewer code expects core to expose (at least) a "check" function (see https://github.com/pi-base/viewer/blob/main/src/reducers.ts line 3), and several other things mentioned in https://github.com/pi-base/viewer/blob/main/src/models/Store/state.ts (traitId, TraitId, defaultHost, ...).

This causes errors when "checking theorems" upon loading the page, producing the message:

    error: TypeError: check is not a function
    columnNumber: 27
    fileName: "http://localhost:3000/src/reducers.ts"
    lineNumber: 25
    message: "check is not a function"
    stack: "reducer<@http://localhost:3000/src/reducers.ts:25:27\ne2/this.produce/un/un<@http://localhost:3000/node_modules/.vite/deps/immer.js?v=37f0cd57:674:35\ne2/this.produce@http://localhost:3000/node_modules/.vite/deps/immer.js?v=37f0cd57:682:16\ne2/this.produce/un@http://localhost:3000/node_modules/.vite/deps/immer.js?v=37f0cd57:672:21\nreducerStore/dispatch/<@http://localhost:3000/src/stores/reducer.ts:5:37\nupdate@http://localhost:3000/node_modules/.vite/deps/chunk-2UOBMVZ2.js?v=37f0cd57:38:9\ndispatch@http://localhost:3000/src/stores/reducer.ts:5:11\ncheck@http://localhost:3000/src/actions.ts:36:13\nrefresh@http://localhost:3000/src/actions.ts:57:11\nasync*boot@http://localhost:3000/src/actions.ts:16:9\ninstance/<@http://localhost:3000/src/App.svelte:199:7\nrun@http://localhost:3000/node_modules/.vite/deps/chunk-7B36NNJA.js?v=37f0cd57:19:10\nmount_component/<@http://localhost:3000/node_modules/.vite/deps/chunk-7B36NNJA.js?v=37f0cd57:1630:39\nflush@http://localhost:3000/node_modules/.vite/deps/chunk-7B36NNJA.js?v=37f0cd57:946:9\ninit@http://localhost:3000/node_modules/.vite/deps/chunk-7B36NNJA.js?v=37f0cd57:1708:5\nApp@http://localhost:3000/src/App.svelte:247:7\ncreateProxiedComponent@http://localhost:3000/node_modules/.pnpm/svelte-hmr@0.14.11_svelte@3.47.0/node_modules/svelte-hmr/runtime/svelte-hooks.js:341:9\nProxyComponent@http://localhost:3000/node_modules/.pnpm/svelte-hmr@0.14.11_svelte@3.47.0/node_modules/svelte-hmr/runtime/proxy.js:242:29\nProxy<App>@http://localhost:3000/node_modules/.pnpm/svelte-hmr@0.14.11_svelte@3.47.0/node_modules/svelte-hmr/runtime/proxy.js:349:11\n@http://localhost:3000/src/index.ts:12:13\n"

This error does not occur if I instead run against the version of @pi-base/core on npm.

**Comment by jamesdabbs** [comment]
Hey @ilcharle 👋🏻 Thanks for filing this issue report, and apologies for missing it earlier. 

@StevenClontz and I have been working on dusting this off and moving things over to the [`pi-base/web`](https://github.com/pi-base/web) monorepo, motivated in part by trying to prevent these sorts of versioning drift issues. We're [actively working on improving the documentation and developer experience there](https://github.com/pi-base/web/pull/52). If you happen to want to kick the tires on any of that and give us feedback, you're certainly welcome to. (We've got Slack notifications set up on `pi-base/web`, so should notice actually notice issues 😅.)
